# Generated by Django 5.2.5 on 2025-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('cloud', 'Cloud'), ('database', 'Database'), ('tools', 'Tools'), ('soft', 'Soft Skill')], max_length=32)),
                ('level', models.PositiveSmallIntegerField(default=70, help_text='0-100 proficiency')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email_public', models.EmailField(blank=True, max_length=254)),
                ('phone_public', models.CharField(blank=True, max_length=50)),
                ('bio_md', models.TextField(blank=True, help_text='Markdown supported')),
                ('resume_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name_plural': 'About me',
                'constraints': [models.UniqueConstraint(fields=('full_name',), name='unique_about_me')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('Backend', 'Backend'), ('Cloud', 'Cloud Architecture')], max_length=20)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('architecture_diagram', models.ImageField(blank=True, null=True, upload_to='architecture_diagrams/')),
                ('featured', models.BooleanField(default=False)),
                ('technologies_used', models.ManyToManyField(blank=True, related_name='projects', to='main.skill')),
            ],
            options={
                'ordering': ['-featured', '-created'],
            },
        ),
    ]
