# Generated by Django 5.2.5 on 2025-09-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certification_remove_aboutme_twitter_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
