# Generated by Django 5.2.5 on 2025-09-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skill_options_remove_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class name (e.g., from Font Awesome)', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Framework', 'Framework'), ('API & Architecture', 'API & Architecture'), ('DevOps & Deployment', 'DevOps & Deployment'), ('Authentication & Security', 'Authentication & Security'), ('Cloud', 'Cloud'), ('Database', 'Database'), ('Tools', 'Tools'), ('Soft Skills', 'Soft Skills')], max_length=32),
        ),
    ]
