# Generated by Django 5.2.5 on 2025-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_icon_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text="Use '-' at the beginning of a line for bullet points. Example:\n- First item\n- Second item\n- Third item"),
        ),
    ]
